Repository PlasmaControl/DESC, pull requests merged in 2023-06, with the labels that each got.

#531 Updates for newer versions of jax
  .github/workflows/jax_tests.yml
  .github/workflows/regression_test.yml
  .github/workflows/unittest.yml
  desc/objectives/objective_funs.py
  devtools/dev-requirements_conda.yml
  requirements.txt
  requirements_conda.yml
Labels: test_jax

#448 Refactor iota computation and add limit
  desc/compute/__init__.py
  desc/compute/_field.py
  desc/compute/_profiles.py
  desc/compute/data_index.py
  desc/compute/utils.py
  desc/equilibrium/configuration.py
  desc/equilibrium/coords.py
  desc/examples/QAS
  desc/examples/QAS_output.h5
  desc/grid.py
  desc/objectives/_bootstrap.py
  desc/objectives/_equilibrium.py
  desc/objectives/_generic.py
  desc/objectives/_geometry.py
  desc/objectives/_qs.py
  desc/objectives/_stability.py
  desc/objectives/utils.py
  docs/adding_objectives.rst
  docs/variables.csv
  tests/test_axis_limits.py
  tests/test_constrain_current.py
  tests/test_objective_funs.py
Labels: good first issue

#501 Function integral
  desc/backend.py
  desc/compat.py
  desc/compute/_bootstrap.py
  desc/compute/_field.py
  desc/compute/_geometry.py
  desc/compute/utils.py
  desc/equilibrium/coords.py
  desc/grid.py
  desc/plotting.py
  desc/vmec.py
  devtools/dev-requirements_conda.yml
  tests/test_axis_limits.py
  tests/test_backend.py
  tests/test_compute_utils.py
  tests/test_grid.py
  tests/test_optimizer.py
Labels: speed, funtionality, run_benchmarks
