Repository PlasmaControl/DESC, pull requests merged in 2023-11, with the labels that each got.

#739 fix inconsistency with the equations on the paper, code and website
  desc/objectives/_equilibrium.py
  docs/theory_general.rst
Labels: EZ-fix

#744 fix installation documentation for using cluster GPUs
  docs/installation.rst
Labels: documentation

#750 instructions for installating DESC on Perlmutter
  docs/installation.rst
Labels: documentation

#751 Update Plot Legend/Label Functionality
  desc/plotting.py
Labels: plotting, EZ-fix
