Repository PlasmaControl/DESC, pull requests merged in 2024-09, with the labels that each got.

#1237 Fix connected theta edges for plot3d
  desc/plotting.py
Labels: plotting, easy

#1241 Resolves #1240
  desc/backend.py
  desc/coils.py
  desc/compute/_basis_vectors.py
  desc/compute/_curve.py
  desc/compute/_equil.py
  desc/compute/_field.py
  desc/compute/_geometry.py
  desc/compute/_metric.py
  desc/compute/_omnigenity.py
  desc/compute/_profiles.py
  desc/compute/_stability.py
  desc/compute/geom_utils.py
  desc/compute/utils.py
  desc/integrals/interp_utils.py
  desc/integrals/singularities.py
  desc/objectives/_coils.py
  desc/objectives/_geometry.py
  desc/utils.py
  tests/test_axis_limits.py
  tests/test_coils.py
  tests/test_compute_funs.py
  tests/test_integrals.py
  tests/test_magnetic_fields.py
Labels: easy

#1246 Have `to_sfl` use NFP in the grids used to fit new Equilibrium
  desc/equilibrium/coords.py
Labels: easy

#1239 Conditional Workflows
  .github/workflows/benchmark.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
Labels: testing, easy

#1247 Add hidden files to upload artifacts step
  .github/workflows/benchmark.yml
Labels: easy, no codecov

#1238 Fix UTC - ET confusion in cache dependency action
  .github/workflows/cache_dependencies.yml
Labels: easy, no codecov

#1248 `flip_theta` compatibility function
  desc/compat.py
  docs/api.rst
  docs/api_equilibrium.rst
  tests/test_compat.py
Labels: interface, easy

#610 change field line integration to use diffrax
  desc/magnetic_fields/_core.py
  devtools/dev-requirements_conda.yml
  requirements.txt
  requirements_conda.yml
  tests/test_magnetic_fields.py
Labels: test_jax, hackathon

#1257 Bump action version and update cached Matplotlib
  .github/workflows/cache_dependencies.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
Labels: easy

#1255 Fix error that can occur when `get_NAE_constraints` is called for only fixing the axis
  desc/objectives/linear_objectives.py
  tests/test_linear_objectives.py
Labels: easy

#1263 Update contributing
  CONTRIBUTING.rst
Labels: easy

#1268 `FixOmniBmax` bug fix
  desc/objectives/linear_objectives.py
  tests/test_linear_objectives.py
Labels: easy, bug fix
