Repository PlasmaControl/DESC, pull requests merged in 2024-06, with the labels that each got.

#1047 Fixes for `jax>=0.4.29` and `interpax==0.3.2`
  desc/singularities.py
  tests/test_curves.py
Labels: EZ-review

#1053 Fix indenting to prevent repeated calculation in check_positive_jacobian()
  desc/compat.py
Labels: EZ-fix, EZ-review

#1054 Add benchmark for running fixed iteration solve
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
Labels: EZ-review

#1066 Remove old `_optimize` method and the test
  desc/equilibrium/equilibrium.py
  tests/test_examples.py
Labels: EZ-review

#1061 Allow `GenericObjective` and `ObjectiveFromUser` to work with generic "things"
  desc/objectives/_generic.py
  docs/notebooks/tutorials/omnigenity.ipynb
  tests/test_examples.py
  tests/test_linear_objectives.py
  tests/test_objective_funs.py
  tests/test_optimizer.py
Labels: funtionality, enhancement, objectives, coil

#1030 ensure correct data types in getter methods
  desc/basis.py
  desc/coils.py
  desc/equilibrium/equilibrium.py
  desc/geometry/core.py
  desc/geometry/curve.py
  desc/geometry/surface.py
  desc/input_reader.py
  desc/io/__init__.py
  desc/io/hdf5_io.py
  desc/io/optimizable_io.py
  desc/objectives/_coils.py
  desc/objectives/objective_funs.py
  desc/profiles.py
  tests/test_objective_funs.py
Labels: bug

#977 Coil-Coil & Plasma-Coil Minimum Distance Objectives
  CHANGELOG.md
  desc/coils.py
  desc/geometry/surface.py
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  desc/objectives/_geometry.py
  desc/optimize/optimizer.py
  tests/test_coils.py
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: coil
