Repository PlasmaControl/DESC, pull requests merged in 2024-12, with the labels that each got.

#1374 Make `factorize_linear_constraints` faster
  desc/objectives/utils.py
  desc/utils.py
  devtools/check_unmarked_tests.sh
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
Labels: performance, skip_changelog

#1419 bug fix for proximal scalar optimization
  CHANGELOG.md
  desc/optimize/_constraint_wrappers.py
  tests/test_optimizer.py
Labels: easy, bug fix

#1422 new profile class `PoweredProfile`
  CHANGELOG.md
  desc/profiles.py
  docs/api.rst
  docs/api_equilibrium.rst
  tests/test_profiles.py
Labels: enhancement, easy

#1003 Effective ripple ε
  desc/compute/__init__.py
  desc/compute/_equil.py
  desc/compute/_neoclassical.py
  desc/compute/_omnigenity.py
  desc/compute/_profiles.py
  desc/compute/_stability.py
  desc/equilibrium/equilibrium.py
  desc/integrals/_bounce_utils.py
  desc/integrals/_interp_utils.py
  desc/integrals/_quad_utils.py
  desc/integrals/basis.py
  desc/integrals/bounce_integral.py
  desc/integrals/quad_utils.py
  desc/objectives/__init__.py
  desc/objectives/_neoclassical.py
  desc/objectives/_stability.py
  desc/objectives/linear_objectives.py
  desc/plotting.py
  desc/utils.py
  docs/adding_objectives.rst
  tests/baseline/test_effective_ripple.png
  tests/baseline/test_fsa_F_normalized.png
  tests/inputs/neo_out.w7x
  tests/test_compute_everything.py
  tests/test_compute_funs.py
  tests/test_examples.py
  tests/test_integrals.py
  tests/test_interp_utils.py
  tests/test_neoclassical.py
  tests/test_objective_funs.py
  tests/test_quad_utils.py
Labels: stable, skip_changelog

#1438 Pin jax version
  devtools/dev-requirements_conda.yml
  requirements.txt
  requirements_conda.yml
Labels: skip_changelog

#1439 Add dependabot config to manage dependency versions
  .github/dependabot.yml
  .github/workflows/benchmark.yml
  .github/workflows/jax_tests.yml
  .github/workflows/mpl_tests.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/weekly_tests.yml
  devtools/dev-requirements_conda.yml
  docs/installation.rst
  requirements.txt
  requirements_conda.yml
Labels: skip_changelog

#1441 Don't mark containers as static unless all members are static
  desc/io/optimizable_io.py
Labels: skip_changelog

#1459 Update dev requirements and remove conda stuff
  .github/dependabot.yml
  .pre-commit-config.yaml
  devtools/dev-requirements.txt
  devtools/dev-requirements_conda.yml
  docs/conf.py
  docs/installation.rst
  requirements_conda.yml
Labels: skip_changelog

#1462 Fix unit tests
  .github/workflows/benchmark.yml
  .github/workflows/black.yml
  .github/workflows/cache_dependencies.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
Labels: bug fix, skip_changelog

#1222 `LinkingCurrent` objective
  CHANGELOG.md
  desc/coils.py
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  docs/api.rst
  docs/api_objectives.rst
  tests/test_objective_funs.py
  tests/test_optimizer.py
Labels: objectives, coil

#1465 bug fix for Profile I/O attributes
  CHANGELOG.md
  desc/profiles.py
  tests/test_input_output.py
Labels: easy, bug fix

#1478 Quad change for speed
  desc/compute/_neoclassical.py
  desc/compute/_neoclassical_1D.py
  desc/objectives/_neoclassical.py
  tests/baseline/test_Gamma_c.png
  tests/baseline/test_Gamma_c_1D.png
Labels: performance

#1476 update Perlmutter installation instructions
  docs/installation.rst
Labels: documentation, easy, skip_changelog

#1475 Add `wb` and `wp` to `VMECIO.save`
  CHANGELOG.md
  desc/vmec.py
  tests/test_vmec.py
Labels: easy

#1363 Update `trust_region_step_exact_` solvers
  desc/examples/__init__.py
  desc/optimize/tr_subproblems.py
  tests/test_optimizer.py
Labels: performance, skip_changelog

#1488 Safediv to avoid nan generation in conngould trust radius...
  desc/optimize/aug_lagrangian.py
  desc/optimize/aug_lagrangian_ls.py
  desc/optimize/fmin_scalar.py
  desc/optimize/least_squares.py
Labels: easy, skip_changelog

#1290 ε and Γ_c with Fourier Bounce
  CHANGELOG.md
  desc/batching.py
  desc/compute/__init__.py
  desc/compute/_deprecated.py
  desc/compute/_fast_ion.py
  desc/compute/_geometry.py
  desc/compute/_neoclassical.py
  desc/equilibrium/coords.py
  desc/grid.py
  desc/integrals/_bounce_utils.py
  desc/integrals/bounce_integral.py
  desc/integrals/quad_utils.py
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  desc/objectives/_fast_ion.py
  desc/objectives/_neoclassical.py
  desc/objectives/_profiles.py
  desc/objectives/_stability.py
  desc/objectives/getters.py
  desc/objectives/linear_objectives.py
  desc/objectives/objective_funs.py
  docs/adding_objectives.rst
  docs/api.rst
  docs/api_objectives.rst
  docs/index.rst
  docs/notebooks/tutorials/EffectiveRipple.ipynb
  docs/write_variables.py
  tests/baseline/test_Gamma_c.png
  tests/baseline/test_Gamma_c_Nemov_1D.png
  tests/baseline/test_Gamma_c_Nemov_2D.png
  tests/baseline/test_Gamma_c_Velasco.png
  tests/baseline/test_Gamma_c_Velasco_1D.png
  tests/baseline/test_Gamma_c_Velasco_2D.png
  tests/baseline/test_binormal_drift_bounce2d.png
  tests/baseline/test_bounce1d_checks.png
  tests/baseline/test_bounce2d_checks.png
  tests/baseline/test_effective_ripple.png
  tests/baseline/test_effective_ripple_1D.png
  tests/baseline/test_effective_ripple_2D.png
  tests/baseline/test_fsa_F_normalized.png
  tests/test_axis_limits.py
  tests/test_compute_everything.py
  tests/test_examples.py
  tests/test_fast_ion.py
  tests/test_integrals.py
  tests/test_neoclassical.py
  tests/test_objective_funs.py
Labels: performance, stable, P3
