Repository PlasmaControl/DESC, pull requests merged in 2024-08, with the labels that each got.

#1167 Add check_intersection flag to the coilset conversion methods
  desc/coils.py
  tests/test_coils.py
Labels: EZ-review

#817 Dp/signed distance
  CHANGELOG.md
  desc/objectives/_geometry.py
  desc/objectives/utils.py
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: Hackathon

#1181 Fix the sign error in wide QR factorization
  desc/optimize/tr_subproblems.py
Labels: Major work, EZ-review

#1140 Change description of `ds` to be clear what it actually is
  desc/compute/_curve.py
Labels: EZ-review

#1198 Improve error msg for plot coils when non-coil object is passed in
  desc/plotting.py
  tests/test_plotting.py
Labels: run_benchmarks

#1192 Simplify normalization scales
  desc/objectives/normalization.py
Labels: EZ-review

#1158 Scaled Linear Constraints
  desc/objectives/utils.py
  desc/optimize/_constraint_wrappers.py
  desc/perturbations.py
  desc/vmec.py
  tests/test_bootstrap.py
  tests/test_linear_objectives.py
  tests/test_optimizer.py
Labels: optimization, coil, EZ-review

#1199 HermiteSplineProfile to improve accuracy of coordinate mapping
  desc/compute/utils.py
  desc/equilibrium/coords.py
  desc/equilibrium/equilibrium.py
  desc/profiles.py
  tests/test_profiles.py
Labels: EZ-review

#1165 Take `p_newton` out of inner while loop
  desc/optimize/aug_lagrangian_ls.py
  desc/optimize/least_squares.py
  desc/optimize/tr_subproblems.py
Labels: easy

#1212 Make integration stuff visible to users and update dev guide
  desc/compute/__init__.py
  desc/compute/_bootstrap.py
  desc/compute/_equil.py
  desc/compute/_field.py
  desc/compute/_geometry.py
  desc/compute/_metric.py
  desc/compute/_profiles.py
  desc/compute/_stability.py
  desc/compute/utils.py
  desc/integrals/__init__.py
  desc/integrals/singularities.py
  desc/integrals/surface_integral.py
  desc/magnetic_fields/_core.py
  desc/objectives/_coils.py
  desc/objectives/_free_boundary.py
  desc/plotting.py
  desc/singularities.py
  desc/vmec.py
  docs/api.rst
  docs/notebooks/dev_guide/grid.ipynb
  tests/test_axis_limits.py
  tests/test_compute_utils.py
  tests/test_integrals.py
  tests/test_plotting.py
  tests/test_singularities.py
Labels: documentation, easy

#1209 change date in docs to be consistent with MM-DD-YYYY format
  docs/installation.rst
Labels: documentation, easy

#1230 Fix `_print_value_fmt` for some objectives and fix some latex labels
  desc/compute/_equil.py
  desc/compute/_field.py
  desc/objectives/_equilibrium.py
  desc/objectives/_power_balance.py
Labels: easy, bug fix

#1213 Higher splitting for Github Actions and Cache venv
  .github/workflows/benchmark.yml
  .github/workflows/black.yml
  .github/workflows/cache_dependencies.yml
  .github/workflows/linting.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/weekly_tests.yml
  tests/benchmarks/compare_bench_results.py
Labels: testing
