Repository PlasmaControl/DESC, pull requests merged in 2024-11, with the labels that each got.

#1345 Add support for benchmark test from forks
  .github/workflows/benchmark.yml
Labels: override codecov

#1356 Fix Extra Benchmark and cancelation
  .github/workflows/benchmark.yml
Labels: easy, skip_changelog

#1358 Add action for checking changelog updates
  .github/workflows/changelog_update.yml
Labels: easy, skip_changelog

#1370 Fix `changelog` workflow
  .github/workflows/changelog_update.yml
Labels: easy, override codecov

#1372 Make scipy requirement uniform across requirements files
  devtools/dev-requirements_conda.yml
  requirements_conda.yml
Labels: easy, skip_changelog

#1401 Let linspace_XXX take in check_intersection
  desc/coils.py
  tests/test_objective_funs.py
Labels: easy, skip_changelog

#1359 Clean up TODOs and FIXMEs
  desc/backend.py
  desc/basis.py
  desc/batching.py
  desc/coils.py
  desc/compute/_geometry.py
  desc/compute/_omnigenity.py
  desc/compute/_profiles.py
  desc/compute/_stability.py
  desc/compute/_surface.py
  desc/continuation.py
  desc/equilibrium/coords.py
  desc/equilibrium/equilibrium.py
  desc/equilibrium/initial_guess.py
  desc/equilibrium/utils.py
  desc/geometry/surface.py
  desc/grid.py
  desc/input_reader.py
  desc/integrals/bounce_utils.py
  desc/integrals/interp_utils.py
  desc/integrals/surface_integral.py
  desc/magnetic_fields/_core.py
  desc/magnetic_fields/_dommaschk.py
  desc/nestor.py
  desc/objectives/_geometry.py
  desc/objectives/linear_objectives.py
  desc/objectives/nae_utils.py
  desc/objectives/objective_funs.py
  desc/optimize/_constraint_wrappers.py
  desc/optimize/_desc_wrappers.py
  desc/optimize/_scipy_wrappers.py
  desc/optimize/aug_lagrangian.py
  desc/optimize/aug_lagrangian_ls.py
  desc/optimize/fmin_scalar.py
  desc/optimize/least_squares.py
  desc/optimize/optimizer.py
  desc/perturbations.py
  desc/plotting.py
  desc/vmec.py
  desc/vmec_utils.py
  devtools/dev-requirements.txt
  devtools/dev-requirements_conda.yml
  tests/baseline/test_plot_poincare.png
  tests/inputs/precise_QA_helical_coils.h5
  tests/test_axis_limits.py
  tests/test_bootstrap.py
  tests/test_compute_everything.py
  tests/test_compute_funs.py
  tests/test_integrals.py
  tests/test_linear_objectives.py
  tests/test_objective_funs.py
  tests/test_plotting.py
Labels: easy, skip_changelog
