Repository PlasmaControl/DESC, pull requests merged in 2024-04, with the labels that each got.

#982 hotfix for `CoilSet` with NFP or stellarator symmetry
  desc/coils.py
  desc/plotting.py
Labels: bug, coil, EZ-review

#726 ko/coils quad flux
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  desc/objectives/getters.py
  desc/optimize/optimizer.py
  desc/singularities.py
  desc/utils.py
  tests/inputs/vacuum_circular_tokamak.h5
  tests/inputs/vacuum_nonaxisym.h5
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: Hackathon

#988 Add documentation for default grid and target/bounds for objectives
  desc/objectives/_bootstrap.py
  desc/objectives/_coils.py
  desc/objectives/_equilibrium.py
  desc/objectives/_free_boundary.py
  desc/objectives/_generic.py
  desc/objectives/_geometry.py
  desc/objectives/_omnigenity.py
  desc/objectives/_profiles.py
  desc/objectives/_stability.py
  desc/objectives/linear_objectives.py
Labels: documentation, EZ-review

#987 Add documentation for compute function keyword arguments
  desc/compute/__init__.py
  desc/compute/_bootstrap.py
  desc/compute/_curve.py
  desc/compute/_equil.py
  desc/compute/_field.py
  desc/compute/_metric.py
  desc/compute/_omnigenity.py
  desc/compute/_surface.py
  desc/compute/data_index.py
  desc/compute/utils.py
  docs/adding_compute_funs.rst
  docs/write_variables.py
Labels: documentation, EZ-review

#984 `TwoPowerProfile`
  desc/profiles.py
  docs/api.rst
  tests/test_profiles.py
Labels: funtionality, EZ-review

#1004 Update requirements and fix conda install
  devtools/dev-requirements_conda.yml
  requirements_conda.yml
Labels: EZ-review
