Repository PlasmaControl/DESC, pull requests merged in 2024-10, with the labels that each got.

#1285 fix bug in `QuasisymmetryBoozer.dim_f`
  desc/objectives/_omnigenity.py
Labels: easy, bug fix

#1289 Add options to plot 3d without any axis visible
  desc/plotting.py
  tests/test_plotting.py
Labels: easy

#1258 Add docstring inheriter
  desc/objectives/_bootstrap.py
  desc/objectives/_coils.py
  desc/objectives/_equilibrium.py
  desc/objectives/_free_boundary.py
  desc/objectives/_generic.py
  desc/objectives/_geometry.py
  desc/objectives/_omnigenity.py
  desc/objectives/_power_balance.py
  desc/objectives/_profiles.py
  desc/objectives/_stability.py
  desc/objectives/objective_funs.py
  docs/adding_objectives.rst
  tests/test_objective_funs.py
Labels: easy

#1305 Add missing unit test markers
  .pre-commit-config.yaml
  desc/objectives/objective_funs.py
  devtools/check_unmarked_tests.sh
  tests/test_curves.py
  tests/test_objective_funs.py
Labels: easy

#1113 Add Coil Arclength Differential Variance Objective
  desc/compute/_curve.py
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  desc/transform.py
  docs/api.rst
  docs/api_objectives.rst
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: coil

#1312 Update matplotlib cache and tests
  .github/workflows/mpl_tests.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
  desc/plotting.py
Labels: test_mpl, easy

#1315 Ensure numpy arrays are not modified in place
  desc/backend.py
Labels: easy

#1326 Fix bug in PlasmaVesselDistance signed distance error checks
  desc/objectives/_geometry.py
  tests/test_objective_funs.py
Labels: easy

#1335 Fixing tiny bug in BallooningStability objective
  desc/objectives/_stability.py
Labels: easy

#1293 Make `map_coordinates` differentiable for JAX `0.4.34`
  .github/workflows/jax_tests.yml
  CHANGELOG.md
  desc/backend.py
  desc/basis.py
  desc/equilibrium/coords.py
  desc/geometry/surface.py
  devtools/dev-requirements_conda.yml
  docs/installation.rst
  requirements.txt
  requirements_conda.yml
  tests/test_backend.py
  tests/test_equilibrium.py
Labels: test_jax, bug fix

#1327 Implement `from_input_file` for `Equilibrium`, update docs with this info
  CHANGELOG.md
  desc/equilibrium/equilibrium.py
  desc/geometry/surface.py
  desc/input_reader.py
  docs/api_equilibrium.rst
  docs/notebooks/tutorials/basic_equilibrium.ipynb
  tests/inputs/input.DSHAPE_desc
  tests/test_input_output.py
Labels: interface, easy

#1338 Run Unmarked Test pre-commit only if all other hooks pass
  .pre-commit-config.yaml
  devtools/check_unmarked_tests.sh
  devtools/clean_logfiles.sh
Labels: override codecov

#1337 Update CHANGELOG
  CHANGELOG.md
Labels: easy, override codecov
