Repository PlasmaControl/DESC, pull requests merged in 2024-05, with the labels that each got.

#1012 Fix definition of b0 in vmec output
  desc/vmec.py
Labels: EZ-review

#956 Dd/optimizable
  desc/backend.py
  desc/basis.py
  desc/objectives/__init__.py
  desc/objectives/_free_boundary.py
  desc/objectives/getters.py
  desc/objectives/linear_objectives.py
  desc/objectives/objective_funs.py
  desc/optimizable.py
  desc/optimize/_constraint_wrappers.py
  desc/utils.py
  docs/api.rst
  docs/api_objectives.rst
  docs/notebooks/tutorials/free_boundary_equilibrium.ipynb
  tests/test_examples.py
  tests/test_linear_objectives.py
  tests/test_optimizer.py
  tests/test_utils.py
Labels: duplicate, funtionality, optimization, coil

#1016 Fix io of MixedCoilSets
  desc/coils.py
  desc/io/hdf5_io.py
  tests/conftest.py
Labels: coil, EZ-review

#1017 `FourierPlanarCurve` basis option
  desc/coils.py
  desc/compute/_curve.py
  desc/geometry/core.py
  desc/geometry/curve.py
  tests/test_curves.py
  tests/test_examples.py
Labels: coil, EZ-review

#1018 `FixCurrents` objective
  desc/objectives/__init__.py
  desc/objectives/linear_objectives.py
  desc/objectives/normalization.py
  tests/conftest.py
  tests/test_linear_objectives.py
Labels: coil, EZ-review
