Repository PlasmaControl/DESC, pull requests merged in 2024-03, with the labels that each got.

#908 Add Bounding Box to Field Line Integration
  CHANGELOG.md
  desc/magnetic_fields.py
  tests/test_magnetic_fields.py
Labels: EZ-review

#917 Rename `eq` method to `equiv` to avoid confusion with `Equilibrium`
  CHANGELOG.md
  desc/io/equilibrium_io.py
  desc/transform.py
  desc/utils.py
  tests/test_coils.py
  tests/test_configuration.py
  tests/test_curves.py
  tests/test_input_output.py
  tests/test_magnetic_fields.py
  tests/test_surfaces.py
  tests/test_transform.py
Labels: EZ-review

#918 Use temp dir for io test
  tests/test_magnetic_fields.py
Labels: EZ-review

#916 Allow shared transforms between R, Z, lambda
  desc/compute/utils.py
  desc/transform.py
Labels: EZ-review

#919 Add option to plot axis position to `plot_boundaries`
  desc/plotting.py
  tests/baseline/test_plot_boundaries.png
Labels: EZ-review

#894 Clean up API for free boundary with surface current
  CHANGELOG.md
  desc/equilibrium/equilibrium.py
  desc/objectives/_free_boundary.py
  docs/notebooks/tutorials/free_boundary_equilibrium.ipynb
  tests/test_objective_funs.py
Labels: EZ-review

#889 Simplify `factorize_linear_constraints`
  desc/backend.py
  desc/geometry/surface.py
  desc/objectives/linear_objectives.py
  desc/objectives/objective_funs.py
  desc/objectives/utils.py
  desc/optimize/_constraint_wrappers.py
  desc/optimize/optimizer.py
  desc/perturbations.py
  desc/vmec.py
  desc/vmec_utils.py
  tests/benchmarks/benchmark_cpu_small.py
  tests/test_examples.py
  tests/test_linear_objectives.py
  tests/test_optimizer.py
Labels: run_benchmarks, objectives

#922 add to CONTRIBUTING.rst how to update master compute data
  CONTRIBUTING.rst
Labels: EZ-review

#931 Change Incompatible constraints to warn, add error if too large of a difference
  desc/objectives/utils.py
  tests/test_linear_objectives.py
Labels: EZ-fix, EZ-review, Hackathon

#925 VMEC wout fixes
  desc/magnetic_fields.py
  desc/vmec.py
  tests/test_vmec.py
Labels: EZ-review

#942 Don't keep reference to data_index in alias partial objects
  desc/compute/data_index.py
Labels: EZ-review

#940 add self_consistency constraints to test
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
Labels: EZ-review

#933 Remove vaccum objective option from ``Equilibrium.solve``
  desc/continuation.py
  desc/equilibrium/equilibrium.py
  desc/input_reader.py
  desc/objectives/getters.py
  tests/conftest.py
  tests/test_input_output.py
Labels: EZ-review

#920 Update API docs
  README.rst
  desc/magnetic_fields/_current_potential.py
  docs/Makefile
  docs/api.rst
  docs/api_continuation.rst
  docs/api_equilibrium.rst
  docs/api_fields.rst
  docs/api_io.rst
  docs/api_objectives.rst
  docs/api_plotting.rst
  docs/binary_output_format.rst
  docs/index.rst
  docs/notebooks/tutorials/advanced_equilibrium_continuation.ipynb
  docs/notebooks/tutorials/advanced_optimization.ipynb
  docs/notebooks/tutorials/basic_equilibrium.ipynb
  docs/notebooks/tutorials/basic_optimization.ipynb
  docs/notebooks/tutorials/nae_constraint.ipynb
Labels: EZ-review

#935 Add field to things for boundary error objectives
  desc/io/equilibrium_io.py
  desc/magnetic_fields/_core.py
  desc/objectives/_free_boundary.py
  docs/notebooks/tutorials/free_boundary_equilibrium.ipynb
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: EZ-review

#853 add basic coil objectives
  desc/backend.py
  desc/coils.py
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  desc/objectives/normalization.py
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: Hackathon

#964 low-beta shifted circle geometric coefficients
  desc/compute/_metric.py
  tests/inputs/low-beta-shifted-circle.h5
  tests/test_axis_limits.py
  tests/test_equilibrium.py
Labels: EZ-review

#969 update changelog for v0.11.1
  CHANGELOG.md
Labels: EZ-review
