Repository PlasmaControl/DESC, pull requests merged in 2024-07, with the labels that each got.

#1091 make VMEC load docstring more clear about what it is doing
  desc/vmec.py
Labels: EZ-review

#1095 Improve warning for missing IOable attributes
  desc/io/hdf5_io.py
Labels: documentation, EZ-review

#1002 Fix JAX error with `FourierCurrentPotentialField` in Flux objectives
  desc/coils.py
  desc/geometry/core.py
  desc/magnetic_fields/_core.py
  desc/magnetic_fields/_current_potential.py
  desc/objectives/_coils.py
  tests/test_coils.py
  tests/test_optimizer.py
Labels: EZ-review

#1124 Document basis for input data
  desc/compute/utils.py
  desc/equilibrium/equilibrium.py
  desc/geometry/core.py
  desc/geometry/curve.py
Labels: documentation, EZ-review

#1125 Add coil objectives to docs
  desc/coils.py
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  docs/api.rst
  docs/api_objectives.rst
  docs/notebooks/zernike_eval.ipynb
  tests/test_examples.py
  tests/test_objective_funs.py
Labels: EZ-review

#1130 `FixSumCoilCurrent` objective
  desc/objectives/__init__.py
  desc/objectives/linear_objectives.py
  docs/api.rst
  docs/api_objectives.rst
  tests/test_linear_objectives.py
Labels: coil, EZ-review

#1134 read VMEC input ZAXIS as ZAXIS_CS
  desc/input_reader.py
Labels: EZ-fix, EZ-review, bug fix

#1024 compute quantities along a fieldline
  desc/backend.py
  desc/compute/_bootstrap.py
  desc/compute/_equil.py
  desc/compute/_field.py
  desc/compute/_geometry.py
  desc/compute/_omnigenity.py
  desc/compute/_profiles.py
  desc/compute/_stability.py
  desc/compute/data_index.py
  desc/compute/utils.py
  desc/equilibrium/coords.py
  desc/equilibrium/equilibrium.py
  desc/grid.py
  desc/utils.py
  tests/test_axis_limits.py
  tests/test_compute_funs.py
  tests/test_compute_utils.py
  tests/test_grid.py
  tests/test_stability_funs.py
Labels: enhancement, Hackathon, bug fix

#1137 Remove basis kwarg from _compute function calls in magnetic field classes
  desc/coils.py
  desc/magnetic_fields/_current_potential.py
  tests/test_coils.py
  tests/test_magnetic_fields.py
Labels: EZ-review

#1056 Execute initializations on CPU much faster
  desc/backend.py
  desc/compute/utils.py
  desc/equilibrium/equilibrium.py
  desc/geometry/surface.py
  desc/objectives/linear_objectives.py
  desc/objectives/objective_funs.py
Labels: EZ-review

#1146 bug fix for `CoilCurrentLength`
  desc/objectives/_coils.py
  tests/test_objective_funs.py
Labels: Urgent, coil, EZ-fix, EZ-review, bug fix

#1142 add knots to attrs
  desc/coils.py
Labels: Urgent

#839 Combine NAE objectives into a single one
  desc/equilibrium/equilibrium.py
  desc/objectives/__init__.py
  desc/objectives/getters.py
  desc/objectives/linear_objectives.py
  desc/objectives/nae_utils.py
  docs/notebooks/tutorials/nae_constraint.ipynb
  tests/test_examples.py
  tests/test_linear_objectives.py
Labels: Urgent, Hackathon

#1116 `from_values` method for `FourierRZCoil` and `FourierPlanarCoil`
  CHANGELOG.md
  desc/coils.py
  desc/geometry/core.py
  desc/geometry/curve.py
  tests/test_coils.py
Labels: Urgent
