Repository PlasmaControl/DESC, pull requests merged in 2025-09, with the labels that each got.

#1896 Pin action-suggester version to 1.22 until a bug is fixed on reviewdog
  .github/workflows/black.yml
Labels: run_benchmarks, easy, skip_changelog

#1884 Throw error in `VMECIO.load` if `lrfp=T`
  desc/vmec.py
Labels: run_benchmarks, easy, skip_changelog

#1842 Always re-solve eq in ProximalProjection before first computation of value and jacobian
  CHANGELOG.md
  desc/optimize/_constraint_wrappers.py
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
  tests/benchmarks/memory_funcs.py
  tests/test_optimizer.py
Labels: easy

#1871 Use ScaledProfile in rescale
  CHANGELOG.md
  desc/compat.py
Labels: run_benchmarks, easy, Bug fix

#1901 fix bug in transform fit when method is jitable
  desc/transform.py
  tests/test_transform.py
Labels: run_benchmarks, skip_changelog
