Repository PlasmaControl/DESC, pull requests merged in 2025-01, with the labels that each got.

#1500 Do not ensure nestedness before fitting geometry of VMEC fit
  desc/vmec.py
Labels: skip_changelog

#1490 enable selecting gpu
  desc/__init__.py
Labels: skip_changelog

#1494 Ku/bounce alpha
  CHANGELOG.md
  desc/compute/_deprecated.py
  desc/compute/_fast_ion.py
  desc/compute/_geometry.py
  desc/compute/_neoclassical.py
  desc/integrals/_bounce_utils.py
  desc/integrals/_interp_utils.py
  desc/integrals/basis.py
  desc/integrals/bounce_integral.py
  desc/integrals/quad_utils.py
  desc/objectives/_fast_ion.py
  desc/objectives/_neoclassical.py
  docs/notebooks/tutorials/EffectiveRipple.ipynb
  docs/write_variables.py
  tests/baseline/test_bounce2d_checks.png
  tests/test_fast_ion.py
  tests/test_integrals.py
  tests/test_neoclassical.py
Labels: stable

#1513 Replace instances of `4pi*1e-7` with `scipy.constants.mu_0`
  desc/coils.py
  desc/integrals/singularities.py
  desc/magnetic_fields/_core.py
  desc/nestor.py
  tests/test_coils.py
Labels: skip_changelog

#1521 Improve handling of Assigning profiles to Equilibrium
  desc/equilibrium/equilibrium.py
  tests/test_equilibrium.py
  tests/test_input_output.py
Labels: easy, skip_changelog

#1483 Fix `objective.compile` in Benchmarks and Miscellaneous stuff
  .github/workflows/benchmark.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  desc/magnetic_fields/_core.py
  desc/objectives/objective_funs.py
  desc/transform.py
  docs/index.rst
  docs/notebooks/tutorials/nae_constraint.ipynb
  docs/performance_tips.rst
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
Labels: easy, skip_changelog

#1536 Free boundary speed
  desc/integrals/singularities.py
  desc/objectives/_free_boundary.py
  desc/transform.py
Labels: performance, easy

#1543 update VMECIO.save defaults
  CHANGELOG.md
  desc/vmec.py
  tests/conftest.py
  tests/test_vmec.py
Labels: interface, easy, P1

#1485 `CoilIntegratedCurvature` objective
  CHANGELOG.md
  desc/objectives/__init__.py
  desc/objectives/_coils.py
  docs/api.rst
  docs/api_objectives.rst
  tests/test_objective_funs.py
Labels: objectives, coil, P2

#1547 update della install instructions
  docs/installation.rst
Labels: easy
