Repository PlasmaControl/DESC, pull requests merged in 2025-07, with the labels that each got.

#1775 Make classes hashable
  desc/basis.py
  desc/objectives/objective_funs.py
  desc/optimize/aug_lagrangian_ls.py
  desc/optimize/least_squares.py
  desc/optimize/tr_subproblems.py
  desc/perturbations.py
  desc/profiles.py
  desc/transform.py
  tests/test_basis.py
  tests/test_transform.py
Labels: run_benchmarks

#1814 Fix circular imports
  desc/coils.py
  desc/compute/__init__.py
  desc/compute/_curve.py
  desc/compute/geom_utils.py
  desc/compute/utils.py
  desc/geometry/core.py
  desc/geometry/curve.py
  desc/geometry/surface.py
  desc/integrals/singularities.py
  desc/magnetic_fields/_core.py
  desc/magnetic_fields/_current_potential.py
  desc/objectives/_coils.py
  desc/objectives/_geometry.py
  desc/utils.py
  publications/panici2022/make_plots_Panici_2022.ipynb
  tests/conftest.py
  tests/test_coils.py
  tests/test_compute_everything.py
  tests/test_compute_funs.py
  tests/test_compute_utils.py
  tests/test_geometry.py
  tests/test_magnetic_fields.py
  tests/test_plotting.py
  tests/test_surfaces.py
Labels: run_benchmarks, skip_changelog

#1806 Updated docs for della install, VMEC input file conversion and objective documentation
  desc/objectives/_generic.py
  docs/dev_guide/adding_objectives.rst
  docs/input.rst
  docs/installation.rst
  docs/notebooks/tutorials/basic_equilibrium.ipynb
Labels: documentation, run_benchmarks, easy, skip_changelog, only-docs-comments

#1622 Ku/cross
  desc/compute/_basis_vectors.py
  desc/compute/_fast_ion.py
  desc/compute/_laplace.py
  desc/compute/_metric.py
  desc/integrals/singularities.py
Labels: empirical, squash

#1825 Ensure correctness in eq.compute for grids spread over multiple field periods
  desc/equilibrium/equilibrium.py
Labels: run_benchmarks, skip_changelog
