Repository PlasmaControl/DESC, pull requests merged in 2025-04, with the labels that each got.

#1679 Small doc update
  docs/notebooks/tutorials/continuation_step_by_step.ipynb
Labels: easy, only-docs-comments

#1600 Simplified Bout computation in free boundary
  desc/integrals/__init__.py
  desc/integrals/_free_boundary.py
  desc/integrals/_vacuum.py
  desc/integrals/singularities.py
  tests/test_integrals.py
Labels: squash

#1685 Fix `test_lstsq`
  desc/objectives/_coils.py
  tests/test_backend.py
Labels: easy, skip_changelog

#1205 Allow `BoundaryError` etc. to take multiple `MagneticField` objects
  desc/objectives/_coils.py
  desc/objectives/_free_boundary.py
  tests/test_objective_funs.py
Labels: objectives, coil, easy, skip_changelog

#1691 Fix `deriv_mode="batched"`
  CHANGELOG.md
  desc/objectives/objective_funs.py
  tests/test_objective_funs.py
Labels: Bug fix

#1670 Add `os.path.expanduser` to `save` and `load` functions
  desc/coils.py
  desc/equilibrium/equilibrium.py
  desc/geometry/curve.py
  desc/geometry/surface.py
  desc/input_reader.py
  desc/io/optimizable_io.py
  desc/magnetic_fields/_core.py
  desc/magnetic_fields/_current_potential.py
  desc/vmec.py
Labels: easy, skip_changelog

#1697 Add 'linear_constraint_options'
  CHANGELOG.md
  desc/optimize/_constraint_wrappers.py
  desc/optimize/optimizer.py
Labels: easy, Bug fix

#1580 Have ``obj.print_value`` return values in a dict
  CHANGELOG.md
  desc/equilibrium/equilibrium.py
  desc/objectives/_free_boundary.py
  desc/objectives/objective_funs.py
  desc/optimize/optimizer.py
  docs/notebooks/tutorials/basic_equilibrium.ipynb
  docs/notebooks/tutorials/basic_optimization.ipynb
  docs/notebooks/tutorials/free_boundary_equilibrium.ipynb
Labels: easy
