Repository PlasmaControl/DESC, pull requests merged in 2025-05, with the labels that each got.

#1702 Optional memory profiler workflow
  .github/workflows/benchmark.yml
  .github/workflows/jax_tests.yml
  .github/workflows/memory_benchmark.yml
  .github/workflows/mpl_tests.yml
  devtools/check_unmarked_tests.sh
  setup.cfg
  tests/benchmarks/compare_mem_results.py
  tests/benchmarks/memory_benchmark_cpu.py
  tests/benchmarks/memory_funcs.py
Labels: skip_changelog

#1713 Add flag to not check intersection when plotting coils
  desc/plotting.py
Labels: skip_changelog

#1688 Reduce storage of big arrays in memory during optimization
  .github/workflows/benchmark.yml
  .github/workflows/memory_benchmark.yml
  CHANGELOG.md
  desc/optimize/aug_lagrangian.py
  desc/optimize/aug_lagrangian_ls.py
  desc/optimize/fmin_scalar.py
  desc/optimize/least_squares.py
  docs/performance_tips.rst
  tests/benchmarks/memory_benchmark_cpu.py
  tests/benchmarks/memory_funcs.py
Labels: run_benchmarks

#1623 Add `blocked` option to `ProximalProjection`
  CHANGELOG.md
  desc/objectives/objective_funs.py
  desc/objectives/utils.py
  desc/optimize/_constraint_wrappers.py
  desc/optimize/least_squares.py
  desc/optimize/optimizer.py
  desc/perturbations.py
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
  tests/test_linear_objectives.py
  tests/test_objective_funs.py
  tests/test_optimizer.py
Labels: performance, run_benchmarks

#1727 Add `source_grid` kwarg to `from_field` for `SplineMagneticField`
  desc/magnetic_fields/_core.py
  tests/test_magnetic_fields.py
Labels: run_benchmarks, easy, skip_changelog

#1734 fix typo in docstring of _adiabatic_J function
  desc/compute/_fast_ion.py
Labels: run_benchmarks

#1741 fix bug in write_vmec_input with spline profiles
  desc/vmec.py
Labels: run_benchmarks, skip_changelog
