Repository PlasmaControl/DESC, pull requests merged in 2025-02, with the labels that each got.

#1552 Add warning for nonzero axis current
  desc/compute/_equil.py
  desc/equilibrium/equilibrium.py
  tests/test_examples.py
  tests/test_linear_objectives.py
  tests/test_objective_funs.py
Labels: skip_changelog

#1560 Improve warning for grids with missing quadrature weights
  desc/grid.py
Labels: skip_changelog

#1565 Update docstring for ObjectiveFromUser
  desc/objectives/_generic.py
Labels: easy, skip_changelog

#1573 JAX environment variable name change
  CHANGELOG.md
  desc/__init__.py
Labels: gpu, dependencies, easy, Bug fix, P3, skip_changelog

#1514 Adding old objectives
  desc/compute/__init__.py
  desc/compute/_neoclassical.py
  desc/compute/_old.py
  desc/integrals/bounce_integral.py
  desc/objectives/_fast_ion.py
  desc/objectives/_neoclassical.py
  desc/objectives/objective_funs.py
  tests/benchmarks/benchmark_cpu_large.py
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_large.py
  tests/benchmarks/benchmark_gpu_small.py
  tests/test_objective_funs.py
Labels: easy, skip_changelog

#1577 Add batched reduction
  desc/backend.py
  desc/batching.py
  desc/integrals/bounce_integral.py
  desc/integrals/singularities.py
Labels: performance, skip_changelog

#1571 Change `maybe_add_self_consistency` to account for multiple objects of same type
  CHANGELOG.md
  desc/objectives/getters.py
  desc/utils.py
  tests/test_optimizer.py
Labels: easy

#1311 Small Miscellaneous coil fixes
  desc/coils.py
Labels: skip_changelog

#1367 Allow compute kwargs to be passed to ``GenericObjective`` and ``ObjectiveFromUser``
  CHANGELOG.md
  desc/examples/__init__.py
  desc/examples/precise_QA.py
  desc/examples/precise_QH.py
  desc/examples/reactor_QA.py
  desc/examples/reactor_QA_output.h5
  desc/examples/regenerate_all_equilibria.py
  desc/objectives/_generic.py
  setup.cfg
  tests/test_objective_funs.py
Labels: easy, Bug fix, P3

#1405 Refactoring `Basis`/`Transform`/`Grid` stuff
  CHANGELOG.md
  desc/basis.py
  desc/equilibrium/coords.py
  desc/grid.py
  desc/plotting.py
  desc/profiles.py
  desc/transform.py
  desc/vmec_utils.py
  tests/test_plotting.py
  tests/test_transform.py
Labels: performance

#1537 Partial summation in bounce integrals
  desc/compute/_fast_ion.py
  desc/integrals/_bounce_utils.py
  desc/integrals/_interp_utils.py
  desc/integrals/basis.py
  desc/integrals/bounce_integral.py
  desc/integrals/singularities.py
  docs/notebooks/tutorials/EffectiveRipple.ipynb
  tests/baseline/test_Gamma_c_Nemov_2D.png
  tests/baseline/test_Gamma_c_Velasco_2D.png
  tests/baseline/test_effective_ripple_2D.png
  tests/test_interp_utils.py
Labels: performance, skip_changelog

#1028 `ExternalObjective` function to wrap external codes
  CHANGELOG.md
  desc/__main__.py
  desc/backend.py
  desc/integrals/surface_integral.py
  desc/objectives/__init__.py
  desc/objectives/_generic.py
  desc/optimize/least_squares.py
  desc/plotting.py
  desc/utils.py
  docs/dev_guide/notebooks/backend.ipynb
  docs/installation.rst
  tests/test_examples.py
  tests/test_objective_funs.py
  tests/test_utils.py
Labels: funtionality, objectives, P2

#1588 Replacing the incomplete integrals for shifted circle test with complete elliptic integrals
  tests/test_integrals.py
Labels: easy

#1596 Make sure users don't use wrong period for coordinate mapping
  desc/grid.py
Labels: skip_changelog

#1593 Fix `.change_resolution(sym=False)` for `FourierRZToroidalSurface`, `ZernikeRZToroidalSection` and `FourierRZCurve`
  CHANGELOG.md
  desc/basis.py
  desc/equilibrium/equilibrium.py
  desc/geometry/curve.py
  desc/geometry/surface.py
  tests/test_curves.py
  tests/test_equilibrium.py
  tests/test_surfaces.py
Labels: easy

#1604 Bug Fix for `ObjectiveFunction._things_per_objective_idx`
  CHANGELOG.md
  desc/objectives/objective_funs.py
  tests/test_objective_funs.py
Labels: easy, Bug fix

#1606 Fix bug that occurs when setting coilset current with a 0-D array
  desc/coils.py
  tests/test_coils.py
Labels: easy, skip_changelog

#1608 Fix asymmetric near axis bug
  CHANGELOG.md
  desc/objectives/linear_objectives.py
  tests/test_linear_objectives.py
Labels: easy
