Repository PlasmaControl/DESC, pull requests merged in 2025-03, with the labels that each got.

#1611 Remove zip strict statement, always attempt broadcast when setting coilset current
  desc/coils.py
Labels: easy, skip_changelog

#1612 Fix bug in surface current field `change_Phi_resolution`
  CHANGELOG.md
  desc/magnetic_fields/_current_potential.py
  tests/test_magnetic_fields.py
Labels: easy

#1546 anisotropy
  CHANGELOG.md
  desc/integrals/singularities.py
  desc/objectives/_free_boundary.py
  docs/notebooks/tutorials/free_boundary_equilibrium.ipynb
  tests/test_integrals.py
Labels: robustness

#1615 Explain to users why variable computations may differ
  desc/compute/_field.py
  desc/integrals/singularities.py
  docs/write_variables.py
Labels: documentation, skip_changelog, squash

#1607 Update docstring for `jac_chunk_size` for ObjectiveFunction with correct default
  desc/objectives/_fast_ion.py
  desc/objectives/_neoclassical.py
  desc/objectives/objective_funs.py
  docs/notebooks/tutorials/EffectiveRipple.ipynb
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
  tests/test_objective_funs.py
Labels: documentation, easy, skip_changelog

#1621 Dump Python 3.9, add support for 3.13
  .github/workflows/benchmark.yml
  .github/workflows/cache_dependencies.yml
  .github/workflows/jax_tests.yml
  .github/workflows/mpl_tests.yml
  .github/workflows/notebook_tests.yml
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/update_notebook_examples.yml
  .github/workflows/weekly_tests.yml
  CHANGELOG.md
  desc/objectives/objective_funs.py
  docs/installation.rst
  setup.py
  tests/benchmarks/compare_bench_results.py
  tests/test_objective_funs.py
Labels: easy

#1613 Ensure correct grid is used for coil biot-savart computation
  desc/coils.py
Labels: skip_changelog

#1630 Fix `test_data_index_deps` for Python 3.13
  desc/objectives/_generic.py
  desc/utils.py
  tests/test_axis_limits.py
  tests/test_data_index.py
Labels: easy, Bug fix, skip_changelog

#1627 fix bug for setting current of `MixedCoilSet`
  CHANGELOG.md
  desc/coils.py
  tests/test_coils.py
Labels: coil, easy, Bug fix

#1582 Make basis modes as static attribute
  desc/equilibrium/equilibrium.py
  desc/geometry/curve.py
  desc/geometry/surface.py
Labels: easy, skip_changelog

#1641 fix `P_fusion` computation
  CHANGELOG.md
  desc/compute/_equil.py
Labels: easy, Bug fix

#1640 Correct cholesky factorized least squares solver
  CHANGELOG.md
  desc/backend.py
  tests/test_backend.py
  tests/test_equilibrium.py
Labels: Bug fix, no squash

#1656 Fix error in AD with default grid for splineXYZCoil
  CHANGELOG.md
  desc/coils.py
  tests/test_objective_funs.py
Labels: easy

#1660 fix bug in`save_in_makegrid_format` for `CoilSet` objects with `sym=True` or `NFP>1`
  CHANGELOG.md
  desc/coils.py
  tests/test_coils.py
Labels: easy
