Repository PlasmaControl/DESC, pull requests merged in 2025-08, with the labels that each got.

#1830 don't close over field in field_line_integrate
  CHANGELOG.md
  desc/magnetic_fields/_core.py
Labels: run_benchmarks, easy

#1828 Fix bug in FourierRZCurve from_values when numpy array is passed
  CHANGELOG.md
  desc/geometry/curve.py
  tests/test_curves.py
Labels: run_benchmarks, easy, Bug fix

#1841 Reuse Z transform for L in from_near_axis
  desc/equilibrium/equilibrium.py
Labels: run_benchmarks, easy, skip_changelog

#1529 adding compute function for gamma integrand
  CHANGELOG.md
  desc/compute/_fast_ion.py
  desc/compute/_neoclassical.py
  desc/plotting.py
  docs/_static/images/plotting/plot_gammac.png
  docs/api.rst
  docs/api_plotting.rst
  tests/baseline/test_plot_gammac.png
  tests/test_plotting.py
Labels: plotting, run_benchmarks

#1862 Fix pip & pytest bug and improve installation
  docs/installation.rst
Labels: documentation, run_benchmarks, skip_changelog, only-docs-comments

#1863 Add static args to Sum and Scaled magnetic field
  desc/magnetic_fields/_core.py
Labels: run_benchmarks, easy, skip_changelog

#1868 Block jax versions 0.5.1 and 0.5.2 which are broken
  requirements.txt
Labels: run_benchmarks, skip_changelog, only-docs-comments

#1867 revert action update until issue #1865 is resolved
  .github/workflows/benchmark.yml
Labels: run_benchmarks, skip_changelog, only-docs-comments

#1874 update changelog with v0.15.0
  CHANGELOG.md
Labels: run_benchmarks, skip_changelog, only-docs-comments

#1881 Ku/finufft gpu
  desc/objectives/_fast_ion.py
  desc/objectives/_neoclassical.py
  docs/installation.rst
  tests/benchmarks/benchmark_cpu_small.py
  tests/benchmarks/benchmark_gpu_small.py
  tests/benchmarks/memory_benchmark_cpu.py
  tests/benchmarks/memory_funcs.py
  tests/test_integrals.py
Labels: skip_changelog
