Repository PlasmaControl/DESC, pull requests merged in 2025-10, with the labels that each got.

#1946 CI related fixes
  .github/workflows/memory_benchmark.yml
  codecov.yml
  tests/benchmarks/compare_bench_results.py
  tests/benchmarks/memory_benchmark_cpu.py
Labels: run_benchmarks, easy, skip_changelog, only-docs-comments

#1839 Updates to `field_line_integrate`
  CHANGELOG.md
  desc/magnetic_fields/_core.py
  desc/plotting.py
  requirements.txt
  tests/test_magnetic_fields.py
  tests/test_plotting.py
Labels: run_benchmarks, easy

#1948 Remove the wrong comment and fix the benchmark comment formatting
  codecov.yml
  tests/benchmarks/compare_bench_results.py
Labels: run_benchmarks, skip_changelog

#1949 Fix failing benchmarks
  desc/objectives/_neoclassical.py
Labels: run_benchmarks, easy, skip_changelog

#1958 Have set initial guess set lambda to zero and update doc
  CHANGELOG.md
  desc/equilibrium/initial_guess.py
Labels: run_benchmarks
