Repository PlasmaControl/DESC, pull requests merged in 2025-06, with the labels that each got.

#1744 Ability to `safenormalize` multiple vectors
  desc/utils.py
  tests/test_utils.py
Labels: run_benchmarks, easy, skip_changelog

#1457 Fix `nan` in reverse mode gradient caused by `rotation_matrix`
  CHANGELOG.md
  desc/compute/_curve.py
  desc/geometry/curve.py
  desc/utils.py
  tests/test_coils.py
  tests/test_objective_funs.py
Labels: run_benchmarks, easy, Bug fix

#1768 Fix small issues
  .github/workflows/regression_tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/update_notebook_examples.yml
  .github/workflows/weekly_tests.yml
  CHANGELOG.md
  tests/test_fast_ion.py
Labels: run_benchmarks, easy, Bug fix, P3

#1770 Add ``meshgrid_flatten`` utility
  CHANGELOG.md
  desc/grid.py
  tests/test_grid.py
Labels: run_benchmarks, easy

#1747 Ability to get eigenfunctions and top k eigenvalues from the ideal ballooning solver.
  CHANGELOG.md
  desc/compute/_stability.py
  desc/objectives/_stability.py
  docs/notebooks/tutorials/ideal_ballooning_stability.ipynb
  tests/test_examples.py
  tests/test_stability_funs.py
Labels: functionality, run_benchmarks

#1762 Correct the description of the coordinate triplet
  desc/compute/_core.py
  desc/compute/_curve.py
  desc/compute/geom_utils.py
  desc/geometry/surface.py
  desc/objectives/_coils.py
Labels: run_benchmarks, P3, skip_changelog, only-docs-comments

#1794 Coil arclength variance for FourierXY
  CHANGELOG.md
  desc/objectives/_coils.py
Labels: run_benchmarks
